name: Backend CI/CD
run-name: ${{ github.actor }} - ${{ github.ref_name }} - [${{ github.sha }}]

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  OS: ubuntu-latest
  IMAGE_REPO: 'test-backend'
  IMAGE_TAG: ${{ github.sha }}
  HELM_RELEASE_NAME: backend
  HELM_NAMESPACE: default

jobs:
  test-code:
    name: Test Code
    # Simulate the utittests (because they are not there)
    runs-on: ${{ .env.OS }}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install test tools
        run: pip install flake8 bandit

      - name: Run flake8 (style checks)
        run: flake8 .

      - name: Run bandit (security checks)
        run: bandit -r .

  build-and-push:
    name: Build and Push Docker Image
    needs: test-code
    runs-on: ${{ .env.OS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ .env.IMAGE_REPO }}:${{ .env.IMAGE_TAG }} .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ .env.IMAGE_REPO }}:${{ .env.IMAGE_TAG }}

  deploy-development:
    name: Deploy to Development
    if: github.event_name == 'push'
    needs: build-and-push
    uses: ./.github/workflows/reusable-deployment.yml
    runs-on: ${{ .env.OS }}
    environment: development
    secrets: inherit
    with:
      ENV: development
      OS: ${{ env.OS }}
      IMAGE_REPO: ${{ env.IMAGE_REPO }}
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
      HELM_RELEASE_NAME: ${{ env.HELM_RELEASE_NAME }}
      HELM_NAMESPACE: ${{ env.HELM_NAMESPACE }}

  deploy-staging:
    name: Deploy to Staging
    if: github.event_name == 'workflow_dispatch'
    needs: build-and-push
    uses: ./.github/workflows/reusable-deployment.yml
    runs-on: ${{ .env.OS }}
    environment: staging
    secrets: inherit
    with:
      ENV: staging
      OS: ${{ env.OS }}
      IMAGE_REPO: ${{ env.IMAGE_REPO }}
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
      HELM_RELEASE_NAME: ${{ env.HELM_RELEASE_NAME }}
      HELM_NAMESPACE: ${{ env.HELM_NAMESPACE }}
