ingressClass: "nginx"
host: ""

basicAuth:
  enabled: true
  basicAuthUsername: placeholder
  basicAuthPassword: placeholder

services:
  - name: "frontend-svc"
    path: "/"
    type: "Exact"
    port: 3000
  - name: "backend-svc"
    path: "/backend"
    type: "Prefix"
    port: 8000
  - name: "kube-prometheus-stack-grafana"
    path: "/grafana(/|$)(.*)"
    type: "ImplementationSpecific"
    port: 80
  - name: "kube-prometheus-stack-prometheus"
    path: "/prometheus(/|$)(.*)"
    type: "ImplementationSpecific"
    port: 9090
