{{- if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-basic-auth-secrets
type: Opaque
data:
  auth: {{ printf "%s:%s" .Values.basicAuth.basicAuthUsername (bcrypt .Values.basicAuth.basicAuthPassword) | b64enc }}
{{- end }}
