apiVersion: batch/v1
kind: Job
metadata:
  name: db-upgrade
spec:
  template:
    spec:
      containers:
        - name: alembic-migration
          image: fredisson11/job-upgrade:1.0.0
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DB_URL
              value: "postgresql://db_user:my_Passwordcln@postgres-postgresql:5432/main_db"
      restartPolicy: Never
  backoffLimit: 4