apiVersion: batch/v1
kind: Job
metadata:
  name: db-upgrade
spec:
  template:
    spec:
      containers:
        - name: alembic-migration
          image: fredisson11/job-upgrade:1.0.0
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: db-secret
      restartPolicy: Never
  backoffLimit: 4