apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-cache-pvc
spec:
  accessModes:
    - {{ .Values.cacheStorage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.cacheStorage.size }}
  storageClassName: {{ .Values.cacheStorage.storageClassName }}