apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: "{{- if kindIs "slice" $val }}{{ join "," $val }}{{ else }}{{ $val }}{{ end }}"
{{- end }}