{{- if or (eq .Values.secrets.DB_USER "placeholder") (eq .Values.secrets.DB_PASSWORD "placeholder") }}
{{- fail "❌ secrets.DB_USER and secrets.DB_PASSWORD must be specified!" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}