{{- if or (eq .Values.secrets.DB_USER "placeholder") (eq .Values.secrets.DB_PASSWORD "placeholder") }}
{{- fail "❌ secrets.DB_USER and secrets.DB_PASSWORD must be specified!" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
