image:
  repository: placeholder
  tag: placeholder
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

service:
  port: 3000
  targetPort: 3000
  type: LoadBalancer

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 70
  memory:
    targetAverageUtilization: 75

cacheStorage:
  enabled: true
  storageClassName: "standard"
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /app/.next/cache

backend:
  url: "http://backend-svc:8000"