image:
  repository: placeholder
  tag: placeholder
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 70
  memory:
    targetAverageUtilization: 75

mediaStorage:
  enabled: true
  storageClassName: "standard"
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /media

config:
  DJANGO_ALLOWED_HOSTS: placeholder # overridden per environment

  DB_HOST: "postgres-postgresql-primary.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: placeholder # overridden per environment

  EMAIL_USE_TLS: "true"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  DEFAULT_FROM_EMAIL: "smtp.tutor.project@gmail.com"

secrets:
  DJANGO_SECRET_KEY: placeholder

  DB_USER: placeholder
  DB_PASSWORD: placeholder

  EMAIL_HOST_USER: placeholder
  EMAIL_HOST_PASSWORD: placeholder

  CELERY_BROKER_URL: placeholder
  CELERY_RESULT_BACKEND: placeholder