image:
  repository: placeholder
  tag: placeholder
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

config:
  DB_HOST: placeholder
  DB_PORT: placeholder
  DB_NAME: placeholder

  EMAIL_HOST: placeholder
  EMAIL_PORT: placeholder
  EMAIL_USE_TLS: placeholder
  DEFAULT_FROM_EMAIL: placeholder

secrets:
  DB_USER: placeholder
  DB_PASSWORD: placeholder

  EMAIL_HOST_USER: placeholder
  EMAIL_HOST_PASSWORD: placeholder

  CELERY_BROKER_URL: placeholder
  CELERY_RESULT_BACKEND: placeholder

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 70
  memory:
    targetAverageUtilization: 75

mediaStorage:
  enabled: false
  storageClassName: "standard"
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /media