name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  test-code:
    runs-on: ubuntu-latest
    continue-on-error: true # Не зупиняємо воркфлоу при помилці
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install test tools
        run: pip install flake8 bandit

      - name: Run flake8 (style checks)
        run: flake8 .

      - name: Run bandit (security checks)
        run: bandit -r .

  build-and-push:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest

  deploy-development:
    if: github.event_name == 'push'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Development
        run: echo "helm upgrade --install backend ./chart --namespace dev"

  deploy-staging:
    if: github.event_name == 'workflow_dispatch'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: echo "helm upgrade --install backend ./chart --namespace staging"