name: Backend CD
run-name: ${{ github.actor }} - ${{ github.ref_name }} - [${{ github.sha }}]

on:
  workflow_dispatch:
    inputs:
      IMAGE_REPO:
        type: string
        required: true
      IMAGE_TAG:
        type: string
        required: true

env:
  ARTIFACT_PATH: 'deploy/inputs.env'

jobs:
  deploy-development:
    name: Deploy to Development
    uses: ./.github/workflows/backend-cd-reusable.yml
    with:
      ENV: development
      IMAGE_REPO: ${{ inputs.IMAGE_REPO }}
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
    secrets: inherit

  save-deploy-inputs:
    name: Save inputs as artifact
    runs-on: ubuntu-latest
    needs: deploy-development

    steps:
    - name: Create deploy metadata
      run: |
        mkdir -p $(dirname "${{ env.ARTIFACT_PATH }}")
        echo "ENV=staging" > ${{ env.ARTIFACT_PATH }}
        echo "IMAGE_REPO=${{ inputs.IMAGE_REPO }}" >> ${{ env.ARTIFACT_PATH }}
        echo "IMAGE_TAG=${{ inputs.IMAGE_TAG }}" >> ${{ env.ARTIFACT_PATH }}

    - name: Upload inputs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-deploy-inputs
        path: ${{ env.ARTIFACT_PATH }}

  prepare-staging:
    name: Prepare inputs for Staging
    runs-on: ubuntu-latest
    needs: save-deploy-inputs

    outputs:
      ENV: ${{ steps.load.outputs.ENV }}
      IMAGE_REPO: ${{ steps.load.outputs.IMAGE_REPO }}
      IMAGE_TAG: ${{ steps.load.outputs.IMAGE_TAG }}

    steps:
      - name: Set artifact directory
        id: set-dir
        run: echo "ARTIFACT_DIR=$(dirname '${{ env.ARTIFACT_PATH }}')" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-deploy-inputs
          path: ${{ env.ARTIFACT_DIR }}

      - name: Load inputs from artifact
        id: load
        run: |
          set -a
          source ${{ env.ARTIFACT_PATH }}
          set +a
          echo "ENV=$ENV" >> $GITHUB_OUTPUT
          echo "IMAGE_REPO=$IMAGE_REPO" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy-staging:
    name: Deploy to Staging
    uses: ./.github/workflows/backend-cd-reusable.yml
    needs: prepare-staging
    with:
      ENV: ${{ needs.prepare-staging.outputs.ENV }}
      IMAGE_REPO: ${{ needs.prepare-staging.outputs.IMAGE_REPO }}
      IMAGE_TAG: ${{ needs.prepare-staging.outputs.IMAGE_TAG }}
    secrets: inherit