name: Migrate DB

on:
  push:
    branches: [main]
    paths:
      - 'db_migrations/**'
      - '.github/workflows/db-migrate.yml'

env:
  DOCKERHUB_REPO: tp154-db_migrations
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    name: Build and Deploy Migration Job
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠 Build and Push Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG ./db_migrations
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
